[package]
name = "uoverse-tools"
version = "0.1.0"
authors = ["Charles Ellis <hamled@hamled.dev>"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
flate2 = "1.0"
thiserror = "1.0"

[[bin]]
name = "mapgen"
