[package]
name = "ultimaonline-net-macros"
version = "0.1.0"
authors = ["Charles Ellis <hamled@hamled.dev>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
syn = "1.0.58"
quote = "1.0.8"
